### ISSUE TITLE
Update Symfony to 3.4

### ISSUE THREAD

**Issue by StudioMaX** [mautic/statsapp#2]
Hey,
When I read the upgrade notes about updating from Mautic 2.x to 3.x, I noticed that the upgrade script sends telemetry to this stats-server. And here I noticed that you are still using Symfony 3.0. God why? Symfony 3.0 hasn't received security fixes since [January 2017](https://symfony.com/releases/3.0) and contains [a lot of CVEs](https://packagist.org/packages/symfony/symfony/advisories?version=926238). I understand that this is a simple internal tool that has quite a few commands. But you must admit that the phrase "each Mautic upgrade or installation sends information about your server to a vulnerable telemetry server" sounds unpleasant :). Moreover, you can upgrade to Symfony 3.4 without any cost.

**Comment by dennisameling** [comment]
@StudioMaX Thank you for creating this issue and for sharing your concern. This repository hasn't been updated since January 2016 and its UI was broken (based on the old Mautic website). I personally wanted to blow new life into this repo and there was a strong wish for the Product team to have Mautic 3 upgrade statistics, so have started by fixing those two things for the Mautic 3 release.

Due to time constraints I haven't been able to update Symfony to 3.4 yet, but am planning to do that towards the end of this week, now that Mautic 3.0.0 and 2.16.3-beta are released (that was the absolute highest prio).

Please be aware that we had and have a massive backlog of things to go through. Getting 3.0.0 released was blocking progress in many other areas, including this repo. Most contributors (including myself) are doing this voluntarily in their free time, so [the more contributors we have](https://contribute.mautic.org/contributing-to-mautic), the better.

If you have resources available to contribute in any way, please reach out to us in the #t-product channel on [Slack](https://www.mautic.org/slack). If you could provide a PR in this repo for the Symfony upgrade that'd be even more awesome.

Once again thanks for sharing your concern, and please know that we're doing as much as we humanly can to push things forward 🚀
